name: Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn nx affected:build --prod --base=origin/master

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Test
        run: |
          yarn nx affected:test --base=origin/master
